// Generated by APEBind. Do not edit directly.
import { fileURLToPath } from 'node:url';

import { APEClient } from './_runtime.js';

const OPERATIONS = {
  "share": {
    "command_path": [
      "share"
    ],
    "execution": "persistent",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json_file",
      "field": "link",
      "option_flag": "--json",
      "ready_timeout_seconds": 20.0,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "share"
        ],
        "token": "share",
        "positionals": [
          {
            "api_name": "paths",
            "required": false,
            "multiple": true
          }
        ],
        "options": [
          {
            "flags": [
              "--version"
            ],
            "primary_flag": "--version",
            "api_name": "version",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--cli"
            ],
            "primary_flag": "--cli",
            "api_name": "cli",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--log-level"
            ],
            "primary_flag": "--log-level",
            "api_name": "logLevel",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--proxy"
            ],
            "primary_flag": "--proxy",
            "api_name": "proxy",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--hook"
            ],
            "primary_flag": "--hook",
            "api_name": "hook",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--enable-reporting"
            ],
            "primary_flag": "--enable-reporting",
            "api_name": "enableReporting",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--name",
              "-n"
            ],
            "primary_flag": "--name",
            "api_name": "name",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--exclude"
            ],
            "primary_flag": "--exclude",
            "api_name": "exclude",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--json"
            ],
            "primary_flag": "--json",
            "api_name": "json",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": true
          },
          {
            "flags": [
              "--upload"
            ],
            "primary_flag": "--upload",
            "api_name": "upload",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--resume"
            ],
            "primary_flag": "--resume",
            "api_name": "resume",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pause"
            ],
            "primary_flag": "--pause",
            "api_name": "pause",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--yes"
            ],
            "primary_flag": "--yes",
            "api_name": "yes",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--legacy-link"
            ],
            "primary_flag": "--legacy-link",
            "api_name": "legacyLink",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--max-downloads"
            ],
            "primary_flag": "--max-downloads",
            "api_name": "maxDownloads",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--timeout"
            ],
            "primary_flag": "--timeout",
            "api_name": "timeout",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--port"
            ],
            "primary_flag": "--port",
            "api_name": "port",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-user"
            ],
            "primary_flag": "--auth-user",
            "api_name": "authUser",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-password"
            ],
            "primary_flag": "--auth-password",
            "api_name": "authPassword",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-auth"
            ],
            "primary_flag": "--recipient-auth",
            "api_name": "recipientAuth",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pickup-code"
            ],
            "primary_flag": "--pickup-code",
            "api_name": "pickupCode",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-public-key"
            ],
            "primary_flag": "--recipient-public-key",
            "api_name": "recipientPublicKey",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-email"
            ],
            "primary_flag": "--recipient-email",
            "api_name": "recipientEmail",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-otp-api-base"
            ],
            "primary_flag": "--recipient-otp-api-base",
            "api_name": "recipientOtpApiBase",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--force-relay"
            ],
            "primary_flag": "--force-relay",
            "api_name": "forceRelay",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--e2ee"
            ],
            "primary_flag": "--e2ee",
            "api_name": "e2ee",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--invite"
            ],
            "primary_flag": "--invite",
            "api_name": "invite",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--qr"
            ],
            "primary_flag": "--qr",
            "api_name": "qr",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--disable-clipboard"
            ],
            "primary_flag": "--disable-clipboard",
            "api_name": "disableClipboard",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--vfs"
            ],
            "primary_flag": "--vfs",
            "api_name": "vfs",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--stdin-cache"
            ],
            "primary_flag": "--stdin-cache",
            "api_name": "stdinCache",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--background"
            ],
            "primary_flag": "--background",
            "api_name": "background",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--foreground"
            ],
            "primary_flag": "--foreground",
            "api_name": "foreground",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--alias"
            ],
            "primary_flag": "--alias",
            "api_name": "alias",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--receipt"
            ],
            "primary_flag": "--receipt",
            "api_name": "receipt",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--receipt-confirm"
            ],
            "primary_flag": "--receipt-confirm",
            "api_name": "receiptConfirm",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--preferred-tunnel"
            ],
            "primary_flag": "--preferred-tunnel",
            "api_name": "preferredTunnel",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "download": {
    "command_path": [
      "download"
    ],
    "execution": "persistent",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "command",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "download"
        ],
        "token": "download",
        "positionals": [
          {
            "api_name": "url",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--version"
            ],
            "primary_flag": "--version",
            "api_name": "version",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--cli"
            ],
            "primary_flag": "--cli",
            "api_name": "cli",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--log-level"
            ],
            "primary_flag": "--log-level",
            "api_name": "logLevel",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--proxy"
            ],
            "primary_flag": "--proxy",
            "api_name": "proxy",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--hook"
            ],
            "primary_flag": "--hook",
            "api_name": "hook",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--enable-reporting"
            ],
            "primary_flag": "--enable-reporting",
            "api_name": "enableReporting",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--output",
              "-o"
            ],
            "primary_flag": "--output",
            "api_name": "outputPath",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--resume"
            ],
            "primary_flag": "--resume",
            "api_name": "resume",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-user"
            ],
            "primary_flag": "--auth-user",
            "api_name": "authUser",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-password"
            ],
            "primary_flag": "--auth-password",
            "api_name": "authPassword",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-auth"
            ],
            "primary_flag": "--recipient-auth",
            "api_name": "recipientAuth",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pickup-code"
            ],
            "primary_flag": "--pickup-code",
            "api_name": "pickupCode",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-private-key"
            ],
            "primary_flag": "--recipient-private-key",
            "api_name": "recipientPrivateKey",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--stdout"
            ],
            "primary_flag": "--stdout",
            "api_name": "stdout",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "keygen": {
    "command_path": [
      "keygen"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": 60.0
    },
    "result": {
      "format": "command",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "keygen"
        ],
        "token": "keygen",
        "positionals": [],
        "options": [
          {
            "flags": [
              "--version"
            ],
            "primary_flag": "--version",
            "api_name": "version",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--cli"
            ],
            "primary_flag": "--cli",
            "api_name": "cli",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--log-level"
            ],
            "primary_flag": "--log-level",
            "api_name": "logLevel",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--proxy"
            ],
            "primary_flag": "--proxy",
            "api_name": "proxy",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--hook"
            ],
            "primary_flag": "--hook",
            "api_name": "hook",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--enable-reporting"
            ],
            "primary_flag": "--enable-reporting",
            "api_name": "enableReporting",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--name"
            ],
            "primary_flag": "--name",
            "api_name": "name",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--share"
            ],
            "primary_flag": "--share",
            "api_name": "share",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--json"
            ],
            "primary_flag": "--json",
            "api_name": "json",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-auth"
            ],
            "primary_flag": "--recipient-auth",
            "api_name": "recipientAuth",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pickup-code"
            ],
            "primary_flag": "--pickup-code",
            "api_name": "pickupCode",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-public-key"
            ],
            "primary_flag": "--recipient-public-key",
            "api_name": "recipientPublicKey",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-email"
            ],
            "primary_flag": "--recipient-email",
            "api_name": "recipientEmail",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-otp-api-base"
            ],
            "primary_flag": "--recipient-otp-api-base",
            "api_name": "recipientOtpApiBase",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "version": {
    "command_path": [
      "share"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": 30.0
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "share"
        ],
        "token": "share",
        "positionals": [
          {
            "api_name": "paths",
            "required": false,
            "multiple": true
          }
        ],
        "options": [
          {
            "flags": [
              "--version"
            ],
            "primary_flag": "--version",
            "api_name": "version",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--cli"
            ],
            "primary_flag": "--cli",
            "api_name": "cli",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--log-level"
            ],
            "primary_flag": "--log-level",
            "api_name": "logLevel",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--proxy"
            ],
            "primary_flag": "--proxy",
            "api_name": "proxy",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--hook"
            ],
            "primary_flag": "--hook",
            "api_name": "hook",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--enable-reporting"
            ],
            "primary_flag": "--enable-reporting",
            "api_name": "enableReporting",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--name",
              "-n"
            ],
            "primary_flag": "--name",
            "api_name": "name",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--exclude"
            ],
            "primary_flag": "--exclude",
            "api_name": "exclude",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--json"
            ],
            "primary_flag": "--json",
            "api_name": "json",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--upload"
            ],
            "primary_flag": "--upload",
            "api_name": "upload",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--resume"
            ],
            "primary_flag": "--resume",
            "api_name": "resume",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pause"
            ],
            "primary_flag": "--pause",
            "api_name": "pause",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--yes"
            ],
            "primary_flag": "--yes",
            "api_name": "yes",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--legacy-link"
            ],
            "primary_flag": "--legacy-link",
            "api_name": "legacyLink",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--max-downloads"
            ],
            "primary_flag": "--max-downloads",
            "api_name": "maxDownloads",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--timeout"
            ],
            "primary_flag": "--timeout",
            "api_name": "timeout",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--port"
            ],
            "primary_flag": "--port",
            "api_name": "port",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-user"
            ],
            "primary_flag": "--auth-user",
            "api_name": "authUser",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-password"
            ],
            "primary_flag": "--auth-password",
            "api_name": "authPassword",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-auth"
            ],
            "primary_flag": "--recipient-auth",
            "api_name": "recipientAuth",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pickup-code"
            ],
            "primary_flag": "--pickup-code",
            "api_name": "pickupCode",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-public-key"
            ],
            "primary_flag": "--recipient-public-key",
            "api_name": "recipientPublicKey",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-email"
            ],
            "primary_flag": "--recipient-email",
            "api_name": "recipientEmail",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-otp-api-base"
            ],
            "primary_flag": "--recipient-otp-api-base",
            "api_name": "recipientOtpApiBase",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--force-relay"
            ],
            "primary_flag": "--force-relay",
            "api_name": "forceRelay",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--e2ee"
            ],
            "primary_flag": "--e2ee",
            "api_name": "e2ee",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--invite"
            ],
            "primary_flag": "--invite",
            "api_name": "invite",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--qr"
            ],
            "primary_flag": "--qr",
            "api_name": "qr",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--disable-clipboard"
            ],
            "primary_flag": "--disable-clipboard",
            "api_name": "disableClipboard",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--vfs"
            ],
            "primary_flag": "--vfs",
            "api_name": "vfs",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--stdin-cache"
            ],
            "primary_flag": "--stdin-cache",
            "api_name": "stdinCache",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--background"
            ],
            "primary_flag": "--background",
            "api_name": "background",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--foreground"
            ],
            "primary_flag": "--foreground",
            "api_name": "foreground",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--alias"
            ],
            "primary_flag": "--alias",
            "api_name": "alias",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--receipt"
            ],
            "primary_flag": "--receipt",
            "api_name": "receipt",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--receipt-confirm"
            ],
            "primary_flag": "--receipt-confirm",
            "api_name": "receiptConfirm",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--preferred-tunnel"
            ],
            "primary_flag": "--preferred-tunnel",
            "api_name": "preferredTunnel",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  }
};
const RUNTIME = {
  "env_unset": [
    "PYTHONHOME",
    "PYTHONPATH",
    "PYTHONSTARTUP",
    "PYTHONDONTWRITEBYTECODE",
    "PYAPP"
  ]
};
const CLIENT = new APEClient(
  fileURLToPath(new URL('./bin/ffl.com', import.meta.url)),
  OPERATIONS,
  RUNTIME,
);

export async function share(parameters = {}) {
  return CLIENT.invoke('share', parameters);
}

export async function download(parameters = {}) {
  return CLIENT.invoke('download', parameters);
}

export async function keygen(parameters = {}) {
  return CLIENT.invoke('keygen', parameters);
}

export async function version(parameters = {}) {
  return CLIENT.invoke('version', parameters);
}

export async function raw(arguments_, options = {}) {
  return CLIENT.raw(arguments_, options);
}
