// Generated by APEBind. Do not edit directly.
import type {
  APEProcessResult,
  ProcessSession,
  RawOptions,
} from './_runtime.js';


export interface ShareParameters {
  paths?: string | readonly string[];
  version?: boolean;
  cli?: boolean;
  logLevel?: string;
  proxy?: string;
  hook?: string;
  enableReporting?: boolean;
  name?: string;
  exclude?: string;
  upload?: boolean | string;
  resume?: boolean;
  pause?: number;
  yes?: boolean;
  legacyLink?: string;
  maxDownloads?: number;
  timeout?: number;
  port?: number;
  authUser?: string;
  authPassword?: string;
  recipientAuth?: string;
  pickupCode?: string;
  recipientPublicKey?: string;
  recipientEmail?: string;
  recipientOtpApiBase?: string;
  forceRelay?: boolean;
  e2ee?: boolean;
  invite?: boolean;
  qr?: boolean | string;
  disableClipboard?: boolean;
  vfs?: boolean;
  stdinCache?: string;
  background?: boolean;
  foreground?: boolean;
  alias?: string;
  receipt?: boolean | string;
  receiptConfirm?: boolean | string;
  preferredTunnel?: string;
}

export function share(
  parameters?: ShareParameters,
): Promise<ProcessSession>;


export interface DownloadParameters {
  url: string;
  version?: boolean;
  cli?: boolean;
  logLevel?: string;
  proxy?: string;
  hook?: string;
  enableReporting?: boolean;
  outputPath?: string;
  resume?: boolean;
  authUser?: string;
  authPassword?: string;
  recipientAuth?: string;
  pickupCode?: string;
  recipientPrivateKey?: string;
  stdout?: boolean;
}

export function download(
  parameters: DownloadParameters,
): Promise<ProcessSession>;


export interface KeygenParameters {
  version?: boolean;
  cli?: boolean;
  logLevel?: string;
  proxy?: string;
  hook?: string;
  enableReporting?: boolean;
  name?: string;
  share?: boolean;
  json?: string;
  recipientAuth?: string;
  pickupCode?: string;
  recipientPublicKey?: string;
  recipientEmail?: string;
  recipientOtpApiBase?: string;
}

export function keygen(
  parameters?: KeygenParameters,
): Promise<APEProcessResult>;


export interface VersionParameters {
  paths?: string | readonly string[];
  version?: boolean;
  cli?: boolean;
  logLevel?: string;
  proxy?: string;
  hook?: string;
  enableReporting?: boolean;
  name?: string;
  exclude?: string;
  json?: string;
  upload?: boolean | string;
  resume?: boolean;
  pause?: number;
  yes?: boolean;
  legacyLink?: string;
  maxDownloads?: number;
  timeout?: number;
  port?: number;
  authUser?: string;
  authPassword?: string;
  recipientAuth?: string;
  pickupCode?: string;
  recipientPublicKey?: string;
  recipientEmail?: string;
  recipientOtpApiBase?: string;
  forceRelay?: boolean;
  e2ee?: boolean;
  invite?: boolean;
  qr?: boolean | string;
  disableClipboard?: boolean;
  vfs?: boolean;
  stdinCache?: string;
  background?: boolean;
  foreground?: boolean;
  alias?: string;
  receipt?: boolean | string;
  receiptConfirm?: boolean | string;
  preferredTunnel?: string;
}

export function version(
  parameters?: VersionParameters,
): Promise<string>;

export function raw(
  arguments_: readonly unknown[],
  options?: RawOptions,
): Promise<APEProcessResult | ProcessSession>;
