// Generated by APEBind. Do not edit directly.
import { spawn } from 'node:child_process';
import { chmodSync, readFileSync, statSync } from 'node:fs';
import { mkdtemp, readFile, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pipeline } from 'node:stream/promises';

export class APEProcessResult {
  constructor(argv, returnCode, stdout, stderr) {
    this.argv = Object.freeze([...argv]);
    this.returnCode = returnCode;
    this.stdout = stdout;
    this.stderr = stderr;
    Object.freeze(this);
  }
}

export class APEEvent {
  constructor(name, data, raw, known) {
    this.name = name;
    this.data = Object.freeze({ ...data });
    this.raw = Object.freeze({ ...raw });
    this.known = known;
    Object.freeze(this);
  }
}

export class APEProcessError extends Error {
  constructor(result) {
    super(
      `APE exited with code ${result.returnCode}: ${result.stderr.trim()}`
      + wslInteropGuidance(result.stderr),
    );
    this.name = 'APEProcessError';
    this.result = result;
  }
}

export class APEEventError extends Error {
  constructor(message, options = {}) {
    super(message, options);
    this.name = 'APEEventError';
  }
}

export class APETimeoutError extends Error {
  constructor(argv, timeoutSeconds) {
    super(`APE did not exit within ${timeoutSeconds} seconds`);
    this.name = 'APETimeoutError';
    this.argv = Object.freeze([...argv]);
    this.timeoutSeconds = timeoutSeconds;
  }
}

function normalizeAPEReturnCode(returnCode) {
  if (
    process.platform === 'win32'
    && returnCode > 0
    && returnCode % 256 === 0
  ) {
    return returnCode / 256;
  }

  return returnCode;
}

function wslInteropGuidance(stderr) {
  if (!stderr.toLowerCase().includes('tlserror([0x6300])')) {
    return '';
  }

  if (!isWSL2()) {
    return '';
  }

  return (
    '\n\nWSL2 may be executing this .com APE through Windows interop. '
    + 'Run the following command in WSL, then restart the WSL session:\n\n'
    + "    sudo sh -c 'echo -1 > /proc/sys/fs/binfmt_misc/WSLInterop'"
  );
}

function isWSL2() {
  let version;

  try {
    version = readFileSync('/proc/version', 'utf8').toLowerCase();
  } catch {
    return false;
  }

  if (!version.includes('microsoft') && !version.includes('wsl')) {
    return false;
  }

  return true;
}

function sleep(milliseconds) {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

function collectStream(stream, capture = true) {
  if (!capture) {
    return () => '';
  }

  const chunks = [];
  stream.on('data', (chunk) => chunks.push(chunk));
  return () => Buffer.concat(chunks).toString('utf8');
}

function waitForExit(child) {
  return new Promise((resolve, reject) => {
    child.once('error', reject);
    child.once('exit', (code, signal) => resolve({ code, signal }));
  });
}

async function waitWithTimeout(promise, timeoutSeconds, onTimeout) {
  if (timeoutSeconds === null || timeoutSeconds === undefined) {
    return promise;
  }

  let timer;

  try {
    return await Promise.race([
      promise,
      new Promise((resolve) => {
        timer = setTimeout(() => {
          onTimeout();
          resolve({ timedOut: true });
        }, timeoutSeconds * 1000);
      }),
    ]);
  } finally {
    clearTimeout(timer);
  }
}

function extractField(value, fieldPath) {
  if (!fieldPath) {
    return value;
  }

  let current = value;

  for (const part of fieldPath.split('.')) {
    current = current[part];
  }

  return current;
}

class RuntimeFiles {
  constructor(directory, paths) {
    this.directory = directory;
    this.paths = Object.freeze({ ...paths });
    this.cleaned = false;
  }

  static async create(operation) {
    const fileNames = {};

    if (operation.result.format === 'json_file') {
      fileNames.result = 'result.json';
    }

    if (operation.events?.source.kind === 'jsonl_file') {
      fileNames.events = 'events.jsonl';
    }

    if (Object.keys(fileNames).length === 0) {
      return null;
    }

    const directory = await mkdtemp(join(tmpdir(), 'apebind-'));
    const paths = Object.fromEntries(
      Object.entries(fileNames).map(([role, fileName]) => [role, join(directory, fileName)]),
    );

    return new RuntimeFiles(directory, paths);
  }

  path(role) {
    return this.paths[role] ?? null;
  }

  async cleanup() {
    if (this.cleaned) {
      return;
    }

    await rm(this.directory, { recursive: true, force: true });
    this.cleaned = true;
  }
}

class EventDecoder {
  constructor(config) {
    this.config = config;
    this.types = new Map(
      config.types.map((eventType) => [eventType.source_value, eventType]),
    );
  }

  _fieldValue(raw, fieldPath) {
    let current = raw;

    for (const part of fieldPath.split('.')) {
      if (
        current === null
        || typeof current !== 'object'
        || !(part in current)
      ) {
        return { found: false, value: undefined };
      }

      current = current[part];
    }

    return { found: true, value: current };
  }

  _validatedValue(eventName, field, value) {
    let valid;

    if (field.value_type === 'string' || field.value_type === 'path') {
      valid = typeof value === 'string';
    } else if (field.value_type === 'boolean') {
      valid = typeof value === 'boolean';
    } else if (field.value_type === 'integer') {
      valid = Number.isInteger(value);
    } else if (field.value_type === 'float') {
      valid = typeof value === 'number' && Number.isFinite(value);
    } else {
      throw new APEEventError(`Unsupported event field type: ${field.value_type}`);
    }

    if (!valid) {
      throw new APEEventError(
        `Event ${eventName} field ${field.name} must be ${field.value_type}`,
      );
    }

    return value;
  }

  decode(line) {
    let raw;

    try {
      raw = JSON.parse(line);
    } catch (error) {
      throw new APEEventError(`Invalid JSONL event: ${JSON.stringify(line)}`, { cause: error });
    }

    if (raw === null || Array.isArray(raw) || typeof raw !== 'object') {
      throw new APEEventError('JSONL event must be a JSON object');
    }

    let sourceName;

    try {
      sourceName = extractField(raw, this.config.discriminator);
    } catch (error) {
      throw new APEEventError(
        `Event is missing discriminator: ${this.config.discriminator}`,
        { cause: error },
      );
    }

    if (typeof sourceName !== 'string' || sourceName.length === 0) {
      throw new APEEventError('Event discriminator must resolve to a non-empty string');
    }

    const eventType = this.types.get(sourceName);
    if (eventType === undefined) {
      return new APEEvent(sourceName, raw, raw, false);
    }

    const data = {};

    for (const eventField of eventType.fields) {
      const field = this._fieldValue(raw, eventField.name);
      if (!field.found) {
        if (eventField.required) {
          throw new APEEventError(
            `Event ${eventType.name} is missing field: ${eventField.name}`,
          );
        }

        continue;
      }

      data[eventField.api_name] = this._validatedValue(
        eventType.name,
        eventField,
        field.value,
      );
    }

    return new APEEvent(eventType.name, data, raw, true);
  }
}

class JSONLFileEventChannel {
  constructor(path, config, isRunning) {
    this.path = path;
    this.decoder = new EventDecoder(config);
    this.isRunning = isRunning;
    this.listeners = new Map();
    this.history = [];
    this.offset = 0;
    this.buffer = '';
    this.error = null;
    this.finished = false;
    this.runPromise = null;
  }

  start() {
    if (this.runPromise !== null) {
      return;
    }

    this.runPromise = this._run();
  }

  async _readNewText() {
    let text;

    try {
      text = await readFile(this.path, 'utf8');
    } catch (error) {
      if (error.code === 'ENOENT') {
        return '';
      }

      throw error;
    }

    if (text.length < this.offset) {
      throw new APEEventError('JSONL event file was truncated while being consumed');
    }

    const chunk = text.slice(this.offset);
    this.offset = text.length;
    return chunk;
  }

  _publish(event) {
    this.history.push(event);

    for (const listener of this.listeners.get(event.name) ?? []) {
      listener(event.data);
    }
  }

  async _consumeAvailable({ final = false } = {}) {
    this.buffer += await this._readNewText();
    const lines = this.buffer.match(/.*(?:\r\n|\n|\r)/g) ?? [];
    const consumedLength = lines.reduce((length, line) => length + line.length, 0);
    this.buffer = this.buffer.slice(consumedLength);

    for (const line of lines) {
      const content = line.trim();
      if (content) {
        this._publish(this.decoder.decode(content));
      }
    }

    if (final && this.buffer.trim()) {
      this._publish(this.decoder.decode(this.buffer.trim()));
      this.buffer = '';
    }
  }

  async _run() {
    try {
      while (this.isRunning()) {
        await this._consumeAvailable();
        await sleep(20);
      }

      await this._consumeAvailable({ final: true });
    } catch (error) {
      this.error = error;
    } finally {
      this.finished = true;
    }
  }

  on(eventName, listener) {
    this.start();

    const listeners = this.listeners.get(eventName) ?? [];
    listeners.push(listener);
    this.listeners.set(eventName, listeners);

    for (const event of this.history) {
      if (event.name === eventName) {
        listener(event.data);
      }
    }
  }

  async *events() {
    this.start();
    let index = 0;

    while (true) {
      if (index < this.history.length) {
        const event = this.history[index];
        index += 1;
        yield event;
        continue;
      }

      if (this.finished) {
        if (this.error !== null) {
          throw this.error;
        }

        return;
      }

      await sleep(20);
    }
  }

  async wait() {
    if (this.runPromise === null) {
      return;
    }

    await this.runPromise;

    if (this.error !== null) {
      throw this.error;
    }
  }
}

export class ProcessSession {
  constructor(
    child,
    argv,
    runtimeFiles = null,
    eventConfig = null,
    { captureStdout = true } = {},
  ) {
    this._child = child;
    this._argv = Object.freeze([...argv]);
    this._runtimeFiles = runtimeFiles;
    this._result = undefined;
    this._processResult = null;
    this._stoppedByClient = false;
    this._returnCode = null;
    this._signal = null;
    this._donePromise = null;
    this._exitListeners = [];
    this._inputSource = null;
    this._inputDone = null;
    this._inputError = null;
    this._captureStdout = captureStdout;
    this._streamedStdoutConsumed = captureStdout;
    this._streamedStdoutIterating = false;
    this._stdoutText = collectStream(child.stdout, captureStdout);
    this._stderrText = collectStream(child.stderr);
    this._exitPromise = waitForExit(child).then((status) => {
      this._signal = status.signal;
      // Windows reports a nonzero status when Node terminates a child process.
      // A client-requested stop is successful regardless of that platform detail.
      this._returnCode = this._stoppedByClient
        ? 0
        : normalizeAPEReturnCode(status.code ?? 1);
      this._stopInputSource();
      this._notifyExitListeners();

      return this._returnCode;
    });
    this._eventChannel = this._createEventChannel(eventConfig);

    if (this._eventChannel !== null) {
      this._eventChannel.start();
    }
  }

  _createEventChannel(eventConfig) {
    if (eventConfig === null || eventConfig === undefined) {
      return null;
    }

    if (this._runtimeFiles === null) {
      throw new Error('Event operation has no runtime-owned files');
    }

    const eventPath = this._runtimeFiles.path('events');
    if (eventPath === null) {
      throw new Error('Event operation has no runtime-owned event path');
    }

    return new JSONLFileEventChannel(eventPath, eventConfig, () => this.running);
  }

  get argv() {
    return this._argv;
  }

  get pid() {
    return this._child.pid;
  }

  get running() {
    return this._returnCode === null && this._child.exitCode === null;
  }

  get returnCode() {
    if (this._returnCode !== null) {
      return this._returnCode;
    }

    if (this._child.exitCode === null) {
      return null;
    }

    return normalizeAPEReturnCode(this._child.exitCode);
  }

  get stdout() {
    return this._child.stdout;
  }

  get stderr() {
    return this._child.stderr;
  }

  get result() {
    return this._result;
  }

  get processResult() {
    return this._processResult;
  }

  get done() {
    if (this._donePromise === null) {
      this._donePromise = this.wait().finally(() => this._cleanupRuntimeFiles());
    }

    return this._donePromise;
  }

  setResult(result) {
    this._result = result;
  }

  onExit(listener) {
    if (typeof listener !== 'function') {
      throw new TypeError('APE exit listener must be a function');
    }

    if (this._returnCode !== null) {
      queueMicrotask(listener);
      return this;
    }

    this._exitListeners.push(listener);
    return this;
  }

  on(eventName, listener) {
    if (this._eventChannel === null) {
      throw new Error('This operation does not define an event stream');
    }

    this._eventChannel.on(eventName, listener);
    return this;
  }

  events() {
    if (this._eventChannel === null) {
      throw new Error('This operation does not define an event stream');
    }

    return this._eventChannel.events();
  }

  async *iterStdout() {
    if (!this._captureStdout) {
      if (this._streamedStdoutIterating) {
        throw new Error('streamed stdout can only be consumed once');
      }

      this._streamedStdoutIterating = true;
      let consumed = false;

      try {
        for await (const chunk of this._child.stdout) {
          yield chunk;
        }

        consumed = true;
      } finally {
        this._streamedStdoutConsumed = consumed;
        this._streamedStdoutIterating = false;

        if (!consumed && !this._child.stdout.destroyed) {
          this._child.stdout.destroy();
        }
      }

      return;
    }

    for await (const chunk of this._child.stdout) {
      yield chunk;
    }
  }

  _attachInput(input) {
    this._inputSource = input;
    this._inputDone = pipeline(input, this._child.stdin).catch((error) => {
      if (
        this._stoppedByClient
        || !this.running
        || error.code === 'EPIPE'
        || error.code === 'ERR_STREAM_PREMATURE_CLOSE'
      ) {
        return;
      }

      this._inputError ??= error;
      this._child.kill('SIGTERM');
    });
  }

  _stopInputSource() {
    if (
      this._inputSource !== null
      && typeof this._inputSource.destroy === 'function'
      && !this._inputSource.destroyed
    ) {
      this._inputSource.destroy();
    }
  }

  async _waitForEventChannel() {
    if (this._eventChannel !== null) {
      await this._eventChannel.wait();
    }
  }

  async _cleanupRuntimeFiles() {
    if (this._runtimeFiles === null) {
      return;
    }

    const runtimeFiles = this._runtimeFiles;
    this._runtimeFiles = null;
    await runtimeFiles.cleanup();
  }

  _notifyExitListeners() {
    const listeners = this._exitListeners;
    this._exitListeners = [];

    for (const listener of listeners) {
      listener();
    }
  }

  _discardStreamedStdout() {
    if (!this._captureStdout && !this._child.stdout.destroyed) {
      this._child.stdout.destroy();
    }
  }

  async _wait(timeoutSeconds = null, { requireStreamedStdout = true } = {}) {
    if (!this._captureStdout && !this._streamedStdoutConsumed) {
      if (requireStreamedStdout) {
        throw new Error('streamed stdout must be consumed before waiting for the process');
      }

      this._discardStreamedStdout();
    }

    let timedOut = false;
    const result = await waitWithTimeout(
      this._exitPromise,
      timeoutSeconds,
      () => {
        timedOut = true;
        this._child.kill('SIGKILL');
      },
    );

    if (timedOut || result?.timedOut) {
      await this._exitPromise.catch(() => undefined);
      throw new APETimeoutError(this._argv, timeoutSeconds);
    }

    const returnCode = await this._exitPromise;
    await this._inputDone;
    await this._waitForEventChannel();

    this._processResult ??= new APEProcessResult(
      this._argv,
      returnCode,
      this._stdoutText(),
      this._stderrText(),
    );

    if (this._inputError !== null && !this._stoppedByClient) {
      throw this._inputError;
    }

    if (returnCode !== 0 && !this._stoppedByClient) {
      throw new APEProcessError(this._processResult);
    }

    return returnCode;
  }

  async wait(timeoutSeconds = null) {
    return this._wait(timeoutSeconds);
  }

  async stop(timeoutSeconds = 5) {
    if (!this.running) {
      try {
        await this._wait(null, { requireStreamedStdout: false });
      } finally {
        await this._cleanupRuntimeFiles();
      }

      return;
    }

    this._stoppedByClient = true;
    this._stopInputSource();
    this._discardStreamedStdout();
    this._child.kill('SIGTERM');
    let timer;

    try {
      await Promise.race([
        this._exitPromise,
        new Promise((resolve) => {
          timer = setTimeout(() => {
            this._child.kill('SIGKILL');
            resolve();
          }, timeoutSeconds * 1000);
        }),
      ]);
      await this._exitPromise;
      await this._waitForEventChannel();
    } finally {
      clearTimeout(timer);
      await this._cleanupRuntimeFiles();
    }
  }

  async close() {
    if (this.running) {
      await this.stop();
      return;
    }

    try {
      await this._wait(null, { requireStreamedStdout: false });
    } finally {
      await this._cleanupRuntimeFiles();
    }
  }
}

export class APEClient {
  constructor(binaryPath, operations, runtime = {}) {
    this._binaryPath = binaryPath;
    this._operations = operations;
    this._runtime = runtime;
  }

  _multipleValues(value) {
    if (typeof value === 'string' || Buffer.isBuffer(value)) {
      return [value];
    }

    if (value !== null && value !== undefined && value[Symbol.iterator]) {
      return value;
    }

    return [value];
  }

  _appendOptionalValue(argv, option, value) {
    if (!option.value_optional) {
      return false;
    }

    if (value === undefined || value === null || value === false) {
      return true;
    }

    argv.push(option.primary_flag);

    if (value === true) {
      return true;
    }

    argv.push(String(value));
    return true;
  }

  _runtimePath(option, runtimeFiles, operation) {
    if (runtimeFiles === null) {
      throw new Error('Runtime-owned option has no runtime files');
    }

    const role = option.runtime_role ?? 'result';
    const path = runtimeFiles.path(role);
    if (path === null) {
      throw new Error(`Runtime-owned option has no ${role} path`);
    }

    const flag = role === 'events'
      ? operation.events.source.option_flag
      : operation.result.option_flag;

    return { flag, path };
  }

  _appendOptions(argv, options, values, runtimeFiles, operation) {
    for (const option of options) {
      if (option.runtime_owned) {
        const runtimePath = this._runtimePath(option, runtimeFiles, operation);
        argv.push(runtimePath.flag, runtimePath.path);
        continue;
      }

      const value = values[option.api_name];
      if (option.boolean) {
        if (value) {
          argv.push(option.primary_flag);
        }

        continue;
      }

      if (this._appendOptionalValue(argv, option, value)) {
        continue;
      }

      if (value === undefined || value === null) {
        if (option.required) {
          throw new TypeError(`Missing required argument: ${option.api_name}`);
        }

        continue;
      }

      if (option.multiple) {
        for (const item of this._multipleValues(value)) {
          argv.push(option.primary_flag, String(item));
        }

        continue;
      }

      argv.push(option.primary_flag, String(value));
    }
  }

  _appendPositionals(argv, positionals, values) {
    for (const positional of positionals) {
      const value = values[positional.api_name];
      if (value === undefined || value === null) {
        if (positional.required) {
          throw new TypeError(`Missing required argument: ${positional.api_name}`);
        }

        continue;
      }

      if (positional.multiple) {
        for (const item of this._multipleValues(value)) {
          argv.push(String(item));
        }

        continue;
      }

      argv.push(String(value));
    }
  }

  _buildArgv(operation, values, runtimeFiles) {
    const argv = [];

    for (const [levelIndex, level] of operation.levels.entries()) {
      if (levelIndex > 0) {
        argv.push(level.token);
      }

      this._appendOptions(
        argv,
        level.options,
        values,
        runtimeFiles,
        operation,
      );
      this._appendPositionals(argv, level.positionals, values);
    }

    return argv;
  }

  _environment() {
    const environment = { ...process.env };

    for (const variableName of this._runtime.env_unset ?? []) {
      delete environment[variableName];
    }

    return environment;
  }

  _launchCommand(argv) {
    if (process.platform === 'win32') {
      return { command: this._binaryPath, args: argv };
    }

    return {
      command: '/bin/sh',
      args: ['-c', 'exec "$0" "$@"', this._binaryPath, ...argv],
    };
  }

  _spawn(argv, stdin = null) {
    const launch = this._launchCommand(argv);

    if (
      process.platform !== 'win32'
      && (statSync(this._binaryPath).mode & 0o111) === 0
    ) {
      chmodSync(this._binaryPath, 0o755);
    }

    return spawn(launch.command, launch.args, {
      env: this._environment(),
      stdio: [stdin === null ? 'ignore' : 'pipe', 'pipe', 'pipe'],
      windowsHide: false,
    });
  }

  async _runCommand(argv, timeoutSeconds = null) {
    const child = this._spawn(argv);
    const stdoutText = collectStream(child.stdout);
    const stderrText = collectStream(child.stderr);
    const exitPromise = waitForExit(child);
    let timedOut = false;
    const status = await waitWithTimeout(
      exitPromise,
      timeoutSeconds,
      () => {
        timedOut = true;
        child.kill('SIGKILL');
      },
    );

    if (timedOut || status?.timedOut) {
      await exitPromise.catch(() => undefined);
      throw new APETimeoutError(argv, timeoutSeconds);
    }

    const completed = await exitPromise;
    const result = new APEProcessResult(
      argv,
      normalizeAPEReturnCode(completed.code ?? 1),
      stdoutText(),
      stderrText(),
    );

    if (result.returnCode !== 0) {
      throw new APEProcessError(result);
    }

    return result;
  }

  _startPersistent(
    argv,
    runtimeFiles,
    eventConfig = null,
    stdin = null,
    sessionOptions = {},
  ) {
    const child = this._spawn(argv, stdin);
    const session = new ProcessSession(
      child,
      argv,
      runtimeFiles,
      eventConfig,
      sessionOptions,
    );

    if (stdin !== null) {
      session._attachInput(stdin);
    }

    return session;
  }

  async _decodeResult(result, resultPath, resultConfig) {
    if (resultConfig.format === 'command') {
      return result;
    }

    if (resultConfig.format === 'text') {
      return resultConfig.strip ? result.stdout.trim() : result.stdout;
    }

    if (resultConfig.format === 'json') {
      return extractField(JSON.parse(result.stdout), resultConfig.field);
    }

    if (resultConfig.format === 'json_file') {
      if (resultPath === null) {
        throw new Error('APE did not create the configured JSON result file');
      }

      const value = JSON.parse(await readFile(resultPath, 'utf8'));
      return extractField(value, resultConfig.field);
    }

    throw new Error(`Unsupported result format: ${resultConfig.format}`);
  }

  async _runOneshot(argv, runtimeFiles, operation) {
    const resultPath = runtimeFiles?.path('result') ?? null;

    try {
      const result = await this._runCommand(
        argv,
        operation.process.timeout_seconds,
      );

      return await this._decodeResult(result, resultPath, operation.result);
    } finally {
      if (runtimeFiles !== null) {
        await runtimeFiles.cleanup();
      }
    }
  }

  async _readJsonResult(resultPath, resultConfig) {
    const value = JSON.parse(await readFile(resultPath, 'utf8'));
    return extractField(value, resultConfig.field);
  }

  async _waitForJsonResult(session, resultPath, resultConfig) {
    if (resultPath === null) {
      throw new Error('JSON result path was not created');
    }

    const timeoutSeconds = Number(resultConfig.ready_timeout_seconds);
    const deadline = Date.now() + timeoutSeconds * 1000;
    let lastSize = -1;
    let stableCount = 0;

    while (Date.now() < deadline) {
      try {
        const fileStat = await stat(resultPath);
        if (fileStat.size > 0 && fileStat.size === lastSize) {
          stableCount += 1;
          if (stableCount >= 2) {
            return await this._readJsonResult(resultPath, resultConfig);
          }
        } else {
          stableCount = 0;
        }

        lastSize = fileStat.size;
      } catch (error) {
        if (error.code !== 'ENOENT') {
          throw error;
        }
      }

      if (!session.running) {
        await session.wait();

        try {
          return await this._readJsonResult(resultPath, resultConfig);
        } catch (error) {
          if (error.code !== 'ENOENT') {
            throw error;
          }

          throw new Error('APE exited before producing the JSON result file');
        }
      }

      await sleep(20);
    }

    throw new APETimeoutError(session.argv, timeoutSeconds);
  }

  async invoke(operationName, values = {}) {
    const operation = this._operations[operationName];
    if (operation === undefined) {
      throw new Error(`Unknown operation: ${operationName}`);
    }

    const runtimeFiles = await RuntimeFiles.create(operation);
    let argv;

    try {
      argv = this._buildArgv(operation, values, runtimeFiles);
    } catch (error) {
      if (runtimeFiles !== null) {
        await runtimeFiles.cleanup();
      }

      throw error;
    }

    if (operation.execution === 'persistent') {
      const session = this._startPersistent(
        argv,
        runtimeFiles,
        operation.events ?? null,
        values.stdin ?? null,
        { captureStdout: values._apebindCaptureStdout ?? true },
      );
      const resultPath = runtimeFiles?.path('result') ?? null;

      try {
        if (
          operation.result.format === 'json_file'
          && operation.result.ready_timeout_seconds !== null
        ) {
          session.setResult(
            await this._waitForJsonResult(session, resultPath, operation.result),
          );
        }
      } catch (error) {
        if (session.running) {
          await session.stop();
        } else {
          await session._cleanupRuntimeFiles();
        }

        throw error;
      }

      return session;
    }

    return this._runOneshot(argv, runtimeFiles, operation);
  }

  async raw(arguments_, { persistent = false, timeoutSeconds = null } = {}) {
    const argv = arguments_.map((value) => String(value));
    if (persistent) {
      return this._startPersistent(argv, null);
    }

    return this._runCommand(argv, timeoutSeconds);
  }
}
