// Generated by APEBind. Do not edit directly.
import type { Readable } from 'node:stream';

export class APEProcessResult {
  constructor(argv: readonly string[], returnCode: number, stdout: string, stderr: string);
  readonly argv: readonly string[];
  readonly returnCode: number;
  readonly stdout: string;
  readonly stderr: string;
}

export class APEEvent<TData = Readonly<Record<string, unknown>>> {
  constructor(
    name: string,
    data: TData,
    raw: Readonly<Record<string, unknown>>,
    known: boolean,
  );
  readonly name: string;
  readonly data: TData;
  readonly raw: Readonly<Record<string, unknown>>;
  readonly known: boolean;
}

export class APEProcessError extends Error {
  constructor(result: APEProcessResult);
  readonly result: APEProcessResult;
}

export class APEEventError extends Error {}

export class APETimeoutError extends Error {
  constructor(argv: readonly string[], timeoutSeconds: number);
  readonly argv: readonly string[];
  readonly timeoutSeconds: number;
}

export type APEEventMap = object;

export class ProcessSession<TEvents extends APEEventMap = Record<string, unknown>> {
  readonly argv: readonly string[];
  readonly pid: number | undefined;
  readonly running: boolean;
  readonly returnCode: number | null;
  readonly stdout: Readable;
  readonly stderr: Readable;
  readonly result: unknown;
  readonly processResult: APEProcessResult | null;
  readonly done: Promise<number>;
  setResult(result: unknown): void;
  on<K extends keyof TEvents & string>(
    eventName: K,
    listener: (data: TEvents[K]) => void,
  ): this;
  events(): AsyncGenerator<APEEvent<TEvents[keyof TEvents]>>;
  iterStdout(): AsyncGenerator<string>;
  wait(timeoutSeconds?: number | null): Promise<number>;
  stop(timeoutSeconds?: number): Promise<void>;
  close(): Promise<void>;
}

export interface RawOptions {
  persistent?: boolean;
  timeoutSeconds?: number | null;
}

export class APEClient {
  constructor(
    binaryPath: string,
    operations: Record<string, unknown>,
    runtime?: Record<string, unknown>,
  );
  invoke(operationName: string, values?: Record<string, unknown>): Promise<unknown>;
  raw(
    arguments_: readonly unknown[],
    options?: RawOptions,
  ): Promise<APEProcessResult | ProcessSession>;
}
